// recipe constant
export const LOAD_RECIPE = 'LOAD_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const ADD_RECIPE = 'ADD_RECIPE'
// user constant
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const USER_LOGUOT = 'USER_LOGUOT'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_TOKEN = 'LOAD_TOKEN'
export const LOAD_RECIPEID = 'LOAD_RECIPEID'
export const LOAD_ADDITIONAL = 'LOAD_ADDITIONAL'
export const ACCEPTED = 'ACCEPTED'
export const USER_DETAIL = 'USER_DETAIL'
// Cart constant
export const CREATE_CART = 'CREATE_CART'
export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const CREATE_ORDER = 'CREATE_ORDER'
export const GET_CART = 'GET_CART'
export const GET_CARTID = 'GET_CARTID'
export const GET_STORE = 'GET_STORE'